version: '3'
services:
  # Node.js application
  node-app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8000:3000"  
    networks:
      - mynetwork
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: Library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # PostgreSQL
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_DB: Library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  
    networks:
      - mynetwork
    volumes:
      - redis-data:/data

networks:
  mynetwork:

volumes:
  postgres-data:
  redis-data:
